//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaglikWebUygulamasi1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HastaneBilgisi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HastaneBilgisi()
        {
            this.Randevu = new HashSet<Randevu>();
        }
    
        public int HastaneBilgisiID { get; set; }
        public int HastaneID { get; set; }
        public int DoktorID { get; set; }
    
        public virtual Doktor Doktor { get; set; }
        public virtual Hastane Hastane { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Randevu> Randevu { get; set; }
    }
}
