//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaglikWebUygulamasi1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HastalikBilgisi
    {
        public int HastaTC { get; set; }
        public int HastalikID { get; set; }
        public int IlacID { get; set; }
        public System.DateTime HastalikTeshisTarihi { get; set; }
        public Nullable<System.DateTime> HastalikIyilestigiTarih { get; set; }
    
        public virtual Hasta Hasta { get; set; }
        public virtual Hastalik Hastalik { get; set; }
        public virtual Ilac Ilac { get; set; }
    }
}
