//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaglikWebUygulamasi1.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public class Login
    {
        public int HastaTC { get; set; }
        public int HastaPassword { get; set; }

        //[JsonIgnore] // Bu özellik JSON dönüþümünde göz ardý edilecek
        public virtual Hasta Hasta { get; set; }
    }
}
