//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaglikWebUygulamasi1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SaglikDBEntities : DbContext
    {
        public SaglikDBEntities()
            : base("name=SaglikDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bolum> Bolum { get; set; }
        public virtual DbSet<Doktor> Doktor { get; set; }
        public virtual DbSet<Hasta> Hasta { get; set; }
        public virtual DbSet<Hastalik> Hastalik { get; set; }
        public virtual DbSet<HastalikBilgisi> HastalikBilgisi { get; set; }
        public virtual DbSet<Hastane> Hastane { get; set; }
        public virtual DbSet<HastaneBilgisi> HastaneBilgisi { get; set; }
        public virtual DbSet<Il> Il { get; set; }
        public virtual DbSet<Ilac> Ilac { get; set; }
        public virtual DbSet<Ilce> Ilce { get; set; }
        public virtual DbSet<Login> Login { get; set; }
        public virtual DbSet<Randevu> Randevu { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TahlilBilgisi> TahlilBilgisi { get; set; }
    }
}
