//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaglikWebUygulamasi1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Randevu
    {
        public int HastaTC { get; set; }
        public int HastaneBilgisiID { get; set; }
        public System.DateTime RandevuTarihi { get; set; }
        public System.TimeSpan RandevuSaati { get; set; }
    
        public virtual Hasta Hasta { get; set; }
        public virtual HastaneBilgisi HastaneBilgisi { get; set; }
    }
}
