//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaglikWebUygulamasi1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TahlilBilgisi
    {
        public int HastaTC { get; set; }
        public System.DateTime TahlilTarihi { get; set; }
        public double Glukoz { get; set; }
        public double Kolestrol { get; set; }
        public double Hemoglobin { get; set; }
        public double KanBasıncı { get; set; }
        public double B12 { get; set; }
        public double A { get; set; }
        public double Kalsiyum { get; set; }
    
        public virtual Hasta Hasta { get; set; }
    }
}
